// Mock expenses data for demonstration
export const mockExpenses = [
  {
    id: "1",
    description: "Home Bills",
    bank: "BNP Bank",
    amount: 50,
    category: "Home",
    type: "expense",
    date: "2026-02-01",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    description: "Electric Bills",
    bank: "BNP Bank",
    amount: 750,
    category: "Bills",
    type: "income",
    date: "2026-02-02",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    description: "Grocery",
    bank: "Citi Bank",
    amount: 220,
    category: "Food",
    type: "expense",
    date: "2026-02-01",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    description: "Salary",
    bank: "BNP Bank",
    amount: 2180,
    category: "Salary",
    type: "income",
    date: "2026-02-01",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    description: "Sport",
    bank: "Cash",
    amount: 38,
    category: "Entertainment",
    type: "expense",
    date: "2026-02-03",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    description: "Shopping",
    bank: "Credit Card",
    amount: 120,
    category: "Shopping",
    type: "expense",
    date: "2026-02-02",
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    description: "Freelance Work",
    bank: "PayPal",
    amount: 500,
    category: "Freelance",
    type: "income",
    date: "2026-02-03",
    createdAt: new Date().toISOString(),
  },
];

export const categoryColors = {
  Home: "#b8860b",
  Bills: "#14b8a6",
  Food: "#ef4444",
  Shopping: "#10b981",
  Entertainment: "#a855f7",
  Transport: "#f59e0b",
  Salary: "#3b82f6",
  Income: "#10b981",
};
